require "spec_helper"
require_relative "../../../plugins/git_commit_message/plugin"

RSpec.describe Norn::Plugins::GitCommitMessage::GitCommitMessagePlugin do
  let(:plugin) { described_class.new }

  describe "Plugin configuration" do
    it "defines the correct plugin name" do
      expect(described_class.plugin_name).to eq("git_commit_message")
    end

    it "subclasses Norn::Plugin" do
      expect(described_class.ancestors).to include(Norn::Plugin)
    end
  end

  describe "#before_git_commit" do
    let(:initial_payload) do
      {
        subcommand: "commit",
        arguments: ["-m", "feat: add super cool helper"]
      }
    end

    before do
      # Back up original configs
      @orig_enabled = Norn.config.git_addon_enabled
      @orig_message = Norn.config.git_addon_message
      @orig_provider = Norn.config.llm_provider
      @orig_openai_model = Norn.config.openai_model
      @orig_gemini_model = Norn.config.gemini_model
    end

    after do
      # Restore original configs
      Norn::Config.config.update(
        git_addon_enabled: @orig_enabled,
        git_addon_message: @orig_message,
        llm_provider: @orig_provider,
        openai_model: @orig_openai_model,
        gemini_model: @orig_gemini_model
      )
    end

    context "when git_addon_enabled is false" do
      before do
        Norn::Config.config.update(git_addon_enabled: false)
      end

      it "returns the payload untouched" do
        result = plugin.before_git_commit(initial_payload)
        expect(result).to eq(initial_payload)
      end
    end

    context "when git_addon_enabled is true" do
      before do
        Norn::Config.config.update(
          git_addon_enabled: true,
          git_addon_message: "Created with the use of LLM via Norn",
          llm_provider: "openai",
          openai_model: "gpt-4o-test-model"
        )
      end

      it "appends the custom message using -m to the arguments" do
        result = plugin.before_git_commit(initial_payload)
        
        expect(result[:arguments]).to eq([
          "-m", "feat: add super cool helper",
          "-m", "Created with the use of gpt-4o-test-model via Norn"
        ])
      end

      it "supports the <model> placeholder as well as LLM" do
        Norn::Config.config.update(git_addon_message: "Generated by <model> with pride")
        
        result = plugin.before_git_commit(initial_payload)
        
        expect(result[:arguments]).to eq([
          "-m", "feat: add super cool helper",
          "-m", "Generated by gpt-4o-test-model with pride"
        ])
      end

      it "correctly resolves the Gemini model if provider is gemini" do
        Norn::Config.config.update(
          llm_provider: "gemini",
          gemini_model: "gemini-test-model"
        )

        result = plugin.before_git_commit(initial_payload)
        
        expect(result[:arguments]).to eq([
          "-m", "feat: add super cool helper",
          "-m", "Created with the use of gemini-test-model via Norn"
        ])
      end
    end
  end
end
